### ISSUE TITLE
 Mount different things over the same mapfile (The other is closed)

### ISSUE THREAD

**Issue by ceso** [Yuav/puppet-autofs#3] opened 2016-02-01 13:46 UTC
Not working, I did the thing you told me in https://github.com/Yuav/puppet-autofs/issues/2 , but is not working yet.
I put the config in type yaml, foreman accept syntax, but if I put in hash, not import the way I worte, they say thats wrong.

And when I wrote two entrys on foreman in mounts, he delete me one of they, for example, if I type within mounts:

'myexample.com':
remote: 'nfs:/example01.com/example'
mountpoint: '/remote/server01
options: 'soft, ro'

'myexample.com':
remote: 'nfs:/example01.com/example2'
mountpoint: '/remote/server/010'
options: 'hard, rw'

or even:

'myexample.com':
remote: 'nfs:/example01.com/example2'
mountpoint: '/remote/server/010'
options: 'hard, rw'

'examples.org':
remote: 'nfs:/server.example.com/test'
mountpoint: '/server/remote/examples'
options: 'hard, rw'

Sometimes foreman delete one of the entrys, even if they are correct.
And sometimes, he accept the two entrys, not delete, and when I run puppet agent in the target host, all run ok, but only apply one of the two entrys that i defined early (with the examples above, for example, only apply either myexample.com, or examples.org, but never bouth.

Do you have idea why this not work? If i did commit a mistake, can you correct me? Or give me a example that works for you in foreman?

Thanks a lot!
And if you can't understand something, please talk me, english isn't my native language.

Regards!
Leandro.

**Comment by Yuav** [comment] 2016-02-01 13:59
Again, this should work in the module. I can't speak for how Foreman treats your variables, but you can manually view the hiera output using:

/etc/puppet/node.rb yournode

You'll then see the actual YAML output that's produced by The Foreman. Ensure this output produce a valid hash map

**Comment by Yuav** [comment] 2016-02-02 14:16
Seems The Foreman doesn't handle YAML all to well, but you can use JSON in place like so:

   [
      {
         "myexample.com":{
            "remote":"nfs:/example01.com/example2",
            "mountpoint":"/remote/server/010",
            "options":"hard, rw"
         }
      },
      {
         "examples.org":{
            "remote":"nfs:/server.example.com/test",
            "mountpoint":"/server/remote/examples",
            "options":"hard, rw"
         }
      }
   ]

**Comment by ceso** [comment] 2016-02-02 14:29
Hi, thanks for your answer, I did try that, and when I run puppet agent, he say

"Error: Could not retrieve catalog from remote server: Error 400 on SERVER: [{"myexample.com"=>{"remote"=>"nfs:/example01.com/example2", "mountpoint"=>"/remote/server/010", "options"=>"hard, rw"}}, {"examples.org"=>{"remote"=>"nfs:/server.example.com/test", "mountpoint"=>"/server/remote/examples", "options"=>"hard, rw"}}] is not a Hash.  It looks to be a Array at /etc/puppet/modules/autofs/manifests/init.pp:63 on node jboss01.app.test.sucive.gub.uy
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run"

If i run ../node.rb myhost, the info about autofs class is:

"classes:
  autofs:
    mounts:
    - myexample.com:
        remote: nfs:/example01.com/example2
        mountpoint: /remote/server/010
        options: hard, rw
    - examples.org:
        remote: nfs:/server.example.com/test
        mountpoint: /server/remote/examples
        options: hard, rw"

So, is ok, but when I run like, says the message above (that is not a hash).

**Comment by Yuav** [comment] 2016-02-02 14:31
Updated my example now

**Comment by ceso** [comment] 2016-02-02 16:45
Well, now works well, only one thing, how have multiples entrys under the same file, your example, creates two files auto.myexample.com and auto.examples.org, but if i want have only a file with they? auto.examples and within it defined two mount entrys? 

I didn't see any parameter with mounts that allow me set a mapping file source.

Regards

**Comment by Yuav** [comment] 2016-02-05 08:08
Could you give me the exact arguments for the module, and configs for;

1. Expected autofs config
2. The actual config

**Comment by ceso** [comment] 2016-02-18 18:59
Hi!!

Continuous with the previous exmaples:

**1. Expected autofs config:**

>    {
      "myexample.com":{
         "remote":"nfs:/example01.com/example2",
         "mountpoint":"/remote/server/010",
         "options":"hard, rw"
      },
      "examples.org":{
         "remote":"nfs:/server.example.com/test",
         "mountpoint":"/server/remote/examples",
         "options":"hard, rw"
      }
   }

Will be produce this:

**auto.master:**

> /- /etc/auto.myexample.com
  /- /etc/auto.examples.org


**auto.myexample.com:**

> \# File managed by puppet, do not edit
   /remote/server/01 hard,rw nfs:/example01.com/example2

**auto.examples.org:**

> \# File managed by puppet, do not edit
   /server/remote/examples hard,rw nfs:/server.example.com/test

**Now, The actual config:**

**auto.master:**

> \# File managed by puppet, do not edit
  /remote/server /etc/auto.myexample.com
  /server/remote /etc/auto.examples.org

**auto.myexample.com:**

> \# File managed by puppet, do not edit
   010 hard, rw nfs:/example01.com/example2

**auto.examples.org**

> \# File managed by puppet, do not edit
   examples hard, rw nfs:/server.example.com/test

So, as you can see, the paths are incorrect, part of they puts in the auto.master and the rest is in the auto.mapping files.

And, as you before requested here is the result of executed /etc/puppet/node.rb mynode (the part that corresponds to autofs calss):

> classes:
>   autofs:
>     mounts:
>       myexample.com:
>         remote: nfs:/example01.com/example2
>         mountpoint: /remote/server/010
>         options: hard, rw
>       examples.org:
>         remote: nfs:/server.example.com/test
>         mountpoint: /server/remote/examples
>         options: hard, rw

Hope this helps, if you need some other dates, please tell me!

Regards!

**Comment by Yuav** [comment] 2016-02-19 12:14
Thank you very much for the detailed error description! I can now easily reproduce the problem, and I'm working on a fix

**Comment by ceso** [comment] 2016-02-19 13:52
Thank so much for your help!

**Comment by Yuav** [comment] 2016-02-19 13:53
This should be fixed in 1.1.8

**Closed by Yuav** 2016-02-19 13:53 UTC

**Comment by ceso** [comment] 2016-02-19 14:14
Well, I'am upgraded now, runing the puppet agent, but not works for me:

The expected config is the same which above.

The actual config after upgraded the module is:

**auto.master:**

> # File managed by puppet, do not edit
> /remote/server /etc/auto._remote_server
> /server/remote /etc/auto._server_remote

**auto._remove_server:**

> 010 hard, rw nfs:/example01.com/example2
> # File managed by puppet, do not edit

**auto._server_remote:**

> examples hard, rw nfs:/server.example.com/test
> # File managed by puppet, do not edit

The dump of /etc/puppet/node.rb mynode is:

classes:
  autofs:
    mounts:
      myexample.com:
        remote: nfs:/example01.com/example2
        mountpoint: /remote/server/010
        options: hard, rw
      examples.org:
        remote: nfs:/server.example.com/test
        mountpoint: /server/remote/examples
        options: hard, rw

(With correct identation)

**Comment by Yuav** [comment] 2016-02-19 18:20
That is actually a design choice. I am using indirect maps instead of direct maps (http://linux.die.net/man/5/auto.master)

This is mainly because indirect maps also creates the base directory (as with mkdir -p) and remove it when the autofs filesystem is umounted
